### ISSUE TITLE
2G MemoryError

### ISSUE THREAD

**Issue by lxstar** [An0nym6/LandlordsEndgame#1]
playerAStr = "2 A A Q Q Q 9 6 4 3 3"
playerBStr = "2 A A K K K J 8 8 6 5 4"
 try it.

will MemoryError, because 32bit 2G top limit.

**Comment by An0nym6** [comment]
Thank you for your attention. This program is a pretty naive implementation of DFS on min-max tree without any heuristic or pruning. It is far from good. It will consume huge memory in complex cases and do unnecessary calculations.

But I'm not going to optimize it cause I'm quite overwhelmed these days. Maybe you can fix it and I would be more than happy to merge it to master.

Thanks again for your issue and sorry for my negligence.
