### ISSUE TITLE
我怎么执行出错？

### ISSUE THREAD

**Issue by jianxintongming** [An0nym6/LandlordsEndgame#2]
if level < 2:
            print '  ' * level * 2 + '正在尝试', i, '/', len(moves)
python新手，没看懂啊，我下载了执行出错，应该怎么修改？

**Comment by An0nym6** [comment]
请提供更多的信息，比如输入是什么，报错是什么。你上面那那两行代码中 print 那一行需要缩进，Python 靠缩进来判断代码块的嵌套关系：

```Python
if level < 2:
  print ' ' * level * 2 + '正在尝试', i, '/', len(moves)
```

**Comment by jianxintongming** [comment]
知道了，你的代码是不是用老版本的python？我新学直接装的最新的python，print需要用括号括起来。。。
